// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_models

type Mutation struct {
}

type Query struct {
}

type CreateServerInput struct {
	Name     string `json:"name"`
	CoverURL string `json:"coverUrl"`
}

type LoginInput struct {
	Credential string `json:"credential"`
	Password   string `json:"password"`
}

type SignupInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
