package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/khalidibnwalid/sadaa/server/internal/graph"
	graph_models "github.com/khalidibnwalid/sadaa/server/internal/graph/models"
	"github.com/khalidibnwalid/sadaa/server/internal/models"
)

// CreateRoomsGroup is the resolver for the createRoomsGroup field.
func (r *mutationResolver) CreateRoomsGroup(ctx context.Context, input graph_models.CreateRoomsGroupInput) (*models.RoomsGroup, error) {
	panic(fmt.Errorf("not implemented: CreateRoomsGroup - createRoomsGroup"))
}

// UpdateRoomsGroup is the resolver for the updateRoomsGroup field.
func (r *mutationResolver) UpdateRoomsGroup(ctx context.Context, id uuid.UUID, input graph_models.UpdateRoomsGroupInput) (*models.RoomsGroup, error) {
	panic(fmt.Errorf("not implemented: UpdateRoomsGroup - updateRoomsGroup"))
}

// RoomsGroups is the resolver for the roomsGroups field.
func (r *queryResolver) RoomsGroups(ctx context.Context, serverID uuid.UUID) ([]*models.RoomsGroup, error) {
	panic(fmt.Errorf("not implemented: RoomsGroups - roomsGroups"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *roomsGroupResolver) CreatedAt(ctx context.Context, obj *models.RoomsGroup) (*time.Time, error) {
	return &obj.CreatedAt.Time, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *roomsGroupResolver) UpdatedAt(ctx context.Context, obj *models.RoomsGroup) (*time.Time, error) {
	return &obj.UpdatedAt.Time, nil
}

// RoomsGroup returns graph.RoomsGroupResolver implementation.
func (r *Resolver) RoomsGroup() graph.RoomsGroupResolver { return &roomsGroupResolver{r} }

type roomsGroupResolver struct{ *Resolver }
