package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/khalidibnwalid/sadaa/server/internal/db"
	"github.com/khalidibnwalid/sadaa/server/internal/graph"
	graph_models "github.com/khalidibnwalid/sadaa/server/internal/graph/models"
	"github.com/khalidibnwalid/sadaa/server/internal/models"
	"github.com/khalidibnwalid/sadaa/server/internal/services/auth"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input graph_models.CreateRoomInput) (*models.Room, error) {
	if !auth.IsAuthed(ctx) {
		return nil, gqlerror.Wrap(ErrUnauthorized)
	}

	room, err := r.DB.CreateRoom(ctx, db.CreateRoomParams{
		Name:       input.Name,
		GroupID:    input.GroupID,
		ServerID:   input.ServerID,
		Type:       input.Type,
		OrderIndex: &input.OrderIndex,
	})

	if err != nil {
		return nil, gqlerror.Wrap(ErrInternalServerError)
	}

	return models.NewRoom(room), nil
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, id uuid.UUID, input graph_models.UpdateRoomInput) (*models.Room, error) {
	panic(fmt.Errorf("not implemented: UpdateRoom - updateRoom"))
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id uuid.UUID) (*models.Room, error) {
	if !auth.IsAuthed(ctx) {
		return nil, gqlerror.Wrap(ErrUnauthorized)
	}
	room, err := r.DB.GetRoomById(ctx, id)
	if err != nil {
		return nil, gqlerror.Wrap(ErrInternalServerError)
	}
	return models.NewRoom(room), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *roomResolver) CreatedAt(ctx context.Context, obj *models.Room) (*time.Time, error) {
	return &obj.CreatedAt.Time, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *roomResolver) UpdatedAt(ctx context.Context, obj *models.Room) (*time.Time, error) {
	return &obj.UpdatedAt.Time, nil
}

// Room returns graph.RoomResolver implementation.
func (r *Resolver) Room() graph.RoomResolver { return &roomResolver{r} }

type roomResolver struct{ *Resolver }
