package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/khalidibnwalid/sadaa/server/internal/graph"
	"github.com/khalidibnwalid/sadaa/server/internal/models"
)

// JoinServer is the resolver for the joinServer field.
func (r *mutationResolver) JoinServer(ctx context.Context, serverID uuid.UUID) (*models.ServerMember, error) {
	panic(fmt.Errorf("not implemented: JoinServer - joinServer"))
}

// GetServersOfUser is the resolver for the getServersOfUser field.
func (r *queryResolver) GetServersOfUser(ctx context.Context) ([]*models.ServerMember, error) {
	panic(fmt.Errorf("not implemented: GetServersOfUser - getServersOfUser"))
}

// GetServerMember is the resolver for the getServerMember field.
func (r *queryResolver) GetServerMember(ctx context.Context, serverID uuid.UUID) (*models.ServerMember, error) {
	panic(fmt.Errorf("not implemented: GetServerMember - getServerMember"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *serverMemberResolver) CreatedAt(ctx context.Context, obj *models.ServerMember) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *serverMemberResolver) UpdatedAt(ctx context.Context, obj *models.ServerMember) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ServerMember returns graph.ServerMemberResolver implementation.
func (r *Resolver) ServerMember() graph.ServerMemberResolver { return &serverMemberResolver{r} }

type serverMemberResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *serverMemberResolver) ID(ctx context.Context, obj *models.ServerMember) (uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
*/
