// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Server struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CoverUrl  *string            `json:"cover_url"`
	CreatorID uuid.UUID          `json:"creator_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ServerMember struct {
	UserID     uuid.UUID          `json:"user_id"`
	ServerID   uuid.UUID          `json:"server_id"`
	Nickname   *string            `json:"nickname"`
	OrderIndex *int32             `json:"order_index"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	AvatarUrl      *string            `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
